// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MigrationFix.Databases;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MigrationFix.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MigrationFix.Models.Zoho.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CustomFieldsValue")
                        .HasColumnType("text")
                        .HasColumnName("CustomFieldsValue");

                    b.Property<string>("FullName")
                        .HasColumnType("text")
                        .HasColumnName("FullName");

                    b.HasKey("Id");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("MigrationFix.Models.Zoho.LeaveRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ApprovalStatus");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreateDateTime");

                    b.Property<Guid>("_employeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("_leaveTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("_employeeId");

                    b.HasIndex("_leaveTypeId");

                    b.ToTable("LeaveRequest", (string)null);
                });

            modelBuilder.Entity("MigrationFix.Models.Zoho.LeaveRequestDays", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("Date");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Duration");

                    b.Property<Guid?>("LeaveRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("_leaveRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LeaveRequestId");

                    b.HasIndex("_leaveRequestId");

                    b.ToTable("LeaveRequestDays", (string)null);
                });

            modelBuilder.Entity("MigrationFix.Models.Zoho.LeaveType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("Type");

                    b.HasKey("Id");

                    b.ToTable("LeaveType", (string)null);
                });

            modelBuilder.Entity("MigrationFix.Models.Zoho.LeaveRequest", b =>
                {
                    b.HasOne("MigrationFix.Models.Zoho.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("_employeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MigrationFix.Models.Zoho.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("_leaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MigrationFix.Models.Zoho.DateInterval", "LeaveDate", b1 =>
                        {
                            b1.Property<Guid>("LeaveRequestId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("From")
                                .HasColumnType("date")
                                .HasColumnName("From");

                            b1.Property<DateOnly>("To")
                                .HasColumnType("date")
                                .HasColumnName("To");

                            b1.HasKey("LeaveRequestId");

                            b1.ToTable("LeaveRequest");

                            b1.WithOwner()
                                .HasForeignKey("LeaveRequestId");
                        });

                    b.Navigation("Employee");

                    b.Navigation("LeaveDate")
                        .IsRequired();

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("MigrationFix.Models.Zoho.LeaveRequestDays", b =>
                {
                    b.HasOne("MigrationFix.Models.Zoho.LeaveRequest", null)
                        .WithMany("LeaveRequestDays")
                        .HasForeignKey("LeaveRequestId");

                    b.HasOne("MigrationFix.Models.Zoho.LeaveRequest", null)
                        .WithMany("LeaveDays")
                        .HasForeignKey("_leaveRequestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("MigrationFix.Models.Zoho.TimeSlot", "TimeSlot", b1 =>
                        {
                            b1.Property<Guid>("LeaveRequestDaysId")
                                .HasColumnType("uuid");

                            b1.Property<TimeOnly>("EndTime")
                                .HasColumnType("time without time zone")
                                .HasColumnName("EndTime");

                            b1.Property<TimeOnly>("StartTime")
                                .HasColumnType("time without time zone")
                                .HasColumnName("StartTime");

                            b1.HasKey("LeaveRequestDaysId");

                            b1.ToTable("LeaveRequestDays");

                            b1.WithOwner()
                                .HasForeignKey("LeaveRequestDaysId");
                        });

                    b.Navigation("TimeSlot")
                        .IsRequired();
                });

            modelBuilder.Entity("MigrationFix.Models.Zoho.LeaveRequest", b =>
                {
                    b.Navigation("LeaveDays");

                    b.Navigation("LeaveRequestDays");
                });
#pragma warning restore 612, 618
        }
    }
}
